---

- hosts: localhost

  pre_tasks:

    - name: fail if the the host's OS isn't supported
      fail:
        msg: This playbook is only compatible with Ubuntu and Pop! OS
      when: >
        (ansible_distribution != "Ubuntu") and
        (ansible_distribution != "Fedora")

  tasks:

    - name: change the hostname if it's given
      hostname:
        name: "{{ hostname }}"
        use: systemd
      when: hostname is defined

    - name: include var files
      include_vars:
        dir: vars

    - name: include packages task
      include_tasks: "tasks/packages-{{ ansible_distribution }}.yml"

    - name: include ssh task
      include_tasks: "tasks/ssh.yml"

    - name: include git task
      include_tasks: "tasks/git.yml"

    - name: include development task
      include_tasks: "tasks/development-{{ ansible_distribution }}.yml"

    - name: include zsh task
      include_tasks: "tasks/zsh.yml"

    - name: include desktop task
      include_tasks: "tasks/desktop-{{ ansible_distribution }}.yml"

    - name: include brave task (Ubuntu)
      include_tasks: "tasks/brave.yml"
      when: ansible_distribution == "Ubuntu"

    - name: include flatpak task
      include_tasks: "tasks/flatpak.yml"
      when: (ansible_virtualization_role == "host") or (ansible_virtualization_role == "N/A")

    - name: include i3 role
      include_role:
        name: i3

# EOF
