---

- name: Install and configure local workstation
  hosts: localhost
  connection: local

  pre_tasks:

    - name: Fail if the distribution isn't supported
      ansible.builtin.fail:
        msg: This playbook is not compatible with your distribution.
      when: >
        (ansible_distribution != "Ubuntu" and ansible_distribution_version != "22.04") and
        (ansible_distribution != "Ubuntu" and ansible_distribution_version != "24.04") and
        (ansible_distribution != "Fedora" and ansible_distribution_major_version != 41)

  tasks:

    - name: Change the hostname if it's given
      ansible.builtin.hostname:
        name: "{{ hostname }}"
        use: systemd
      when: hostname is defined

    - name: Include base role
      ansible.builtin.include_role:
        name: base
        apply:
          tags:
            - base
      tags:
        - base

    - name: Include the neovim role
      ansible.builtin.include_role:
        name: neovim
        apply:
          tags:
            - neovim
      tags:
        - neovim

    - name: Include ssh role
      ansible.builtin.include_role:
        name: ssh
        apply:
          tags:
            - ssh
      tags:
        - ssh

    - name: Include git role
      ansible.builtin.include_role:
        name: git
        apply:
          tags:
            - git
      tags:
        - git

    - name: Include brave role
      ansible.builtin.include_role:
        name: brave
        apply:
          tags:
            - brave
      tags:
        - brave
      when: ansible_facts['virtualization_type'] != "wsl"

    - name: Include tailscale role
      ansible.builtin.include_role:
        name: tailscale
        apply:
          tags:
            - tailscale
      tags:
        - tailscale
      when: ansible_facts['virtualization_type'] != "wsl"

    - name: Include flatpak task
      ansible.builtin.include_role:
        name: flatpak
        apply:
          tags:
            - flatpak
      tags:
        - flatpak
      when: ansible_facts['virtualization_type'] != "wsl"

    - name: Include gnome role
      ansible.builtin.include_role:
        name: gnome
        apply:
          tags:
            - gnome
      tags:
        - gnome
      when: ansible_facts['virtualization_type'] != "wsl"

    - name: Include nvidia driver role
      ansible.builtin.include_role:
        name: nvidia
        apply:
          tags:
            - nvidia
      tags:
        - nvidia
        - never

# EOF
