---
- name: Install and configure local workstation
  hosts: localhost
  connection: local

  pre_tasks:
    - name: Fail if the distribution isn't supported
      ansible.builtin.fail:
        msg: This playbook is not compatible with your distribution.
      when: >
        (ansible_distribution != "Ubuntu" and ansible_distribution_version != "22.04") and
        (ansible_distribution != "Ubuntu" and ansible_distribution_version != "24.04") and
        (ansible_distribution != "Fedora" and ansible_distribution_major_version != 42)

  tasks:
    - name: Change the hostname if it's given
      ansible.builtin.hostname:
        name: "{{ hostname }}"
        use: systemd
      when: hostname is defined

  roles:
    - role: base
      tags:
        - base

    - role: neovim
      tags:
        - neovim

    - role: ssh
      tags:
        - ssh

    - role: git
      tags:
        - git

    - role: tailscale
      tags:
        - tailscale
      when: ansible_facts['virtualization_type'] != "wsl"

    - role: flatpak
      tags:
        - flatpak
      when: ansible_facts['virtualization_type'] != "wsl"

    - role: gnome
      tags:
        - gnome
      when: ansible_facts['virtualization_type'] != "wsl"

    - role: nvidia
      tags:
        - nvidia
        - never
# EOF
