---

- hosts: localhost

  pre_tasks:

    - name: fail if the the distribution isn't supported
      ansible.builtin.fail:
        msg: This playbook is not compatible with your distribution.
      when: >
        (ansible_distribution != "Ubuntu" and ansible_distribution_version != "22.04") and
        (ansible_distribution != "Fedora" and ansible_distribution_major_version != 39) and
        (ansible_distribution != "Fedora" and ansible_distribution_major_version != 40) and
        (ansible_distribution != "PopOS!" and ansible_distribution_version != "22.04")

    - name: set default theme
      ansible.builtin.set_fact:
        theme: nord

  tasks:

    - name: change the hostname if it's given
      ansible.builtin.hostname:
        name: "{{ hostname }}"
        use: systemd
      when: hostname is defined

    - name: include var files
      ansible.builtin.include_vars:
        dir: vars

    - name: include packages task
      ansible.builtin.include_tasks: "tasks/packages-{{ ansible_os_family }}.yml"

    - name: include ssh task
      ansible.builtin.include_tasks: "tasks/ssh.yml"

    - name: include git task
      ansible.builtin.include_tasks: "tasks/git.yml"

    - name: include development task
      ansible.builtin.include_tasks: "tasks/development-{{ ansible_os_family }}.yml"

    - name: include zsh task
      ansible.builtin.include_tasks: "tasks/zsh.yml"
      tags: zsh

    - name: include desktop task
      ansible.builtin.include_tasks: "tasks/desktop-{{ ansible_os_family }}.yml"

    - name: include brave task
      ansible.builtin.include_tasks: "tasks/brave-{{ ansible_os_family }}.yml"

    - name: include flatpak task
      ansible.builtin.include_tasks: "tasks/flatpak.yml"
      when: (ansible_virtualization_role == "host") or (ansible_virtualization_role == "N/A")

    - name: include i3 role
      ansible.builtin.include_role:
        name: i3
        apply:
          tags:
            - i3
      tags:
        - i3
        - never

    - name: include gnome role
      ansible.builtin.include_role:
        name: gnome
        apply:
          tags:
            - gnome
      tags:
        - gnome

    - name: include nvidia driver install task
      ansible.builtin.include_tasks: "tasks/nvidia-{{ ansible_os_family }}.yml"
      tags:
        - nvidia
        - never

# EOF
