---

- hosts: localhost

  pre_tasks:

    - name: fail if the the distribution isn't supported
      ansible.builtin.fail:
        msg: This playbook is only compatible with Ubuntu 22 and Fedora 38.
      when: >
        (ansible_distribution != "Ubuntu" and ansible_distribution_major_version == 22) or
        (ansible_distribution != "Fedora" and ansible_distribution_major_version == 38)

  tasks:

    - name: change the hostname if it's given
      ansible.builtin.hostname:
        name: "{{ hostname }}"
        use: systemd
      when: hostname is defined

    - name: include var files
      ansible.builtin.include_vars:
        dir: vars

    - name: include packages task
      ansible.builtin.include_tasks: "tasks/packages-{{ ansible_distribution }}.yml"

    - name: include ssh task
      ansible.builtin.include_tasks: "tasks/ssh.yml"

    - name: include git task
      ansible.builtin.include_tasks: "tasks/git.yml"

    - name: include development task
      ansible.builtin.include_tasks: "tasks/development-{{ ansible_distribution }}.yml"

    - name: include zsh task
      ansible.builtin.include_tasks: "tasks/zsh.yml"

    - name: include desktop task
      ansible.builtin.include_tasks: "tasks/desktop-{{ ansible_distribution }}.yml"

    - name: include brave task (Ubuntu)
      ansible.builtin.include_tasks: "tasks/brave-{{ ansible_distribution }}.yml"

    - name: include flatpak task
      ansible.builtin.include_tasks: "tasks/flatpak.yml"
      when: (ansible_virtualization_role == "host") or (ansible_virtualization_role == "N/A")

    - name: include i3 role
      ansible.builtin.include_role:
        name: i3
        apply:
          tags:
            - i3
      tags:
        - i3
        - never

# EOF
