---

- name: Install and configure local workstation
  hosts: localhost
  connection: local

  pre_tasks:

    - name: Fail if the the distribution isn't supported
      ansible.builtin.fail:
        msg: This playbook is not compatible with your distribution.
      when: >
        (ansible_distribution != "Fedora" and ansible_distribution_major_version != 40)

    - name: Set default theme
      ansible.builtin.set_fact:
        theme: nord

  tasks:

    - name: Change the hostname if it's given
      ansible.builtin.hostname:
        name: "{{ hostname }}"
        use: systemd
      when: hostname is defined

    - name: Include var files
      ansible.builtin.include_vars:
        dir: vars

    - name: Include packages task
      ansible.builtin.include_tasks: "tasks/packages.yml"

    - name: Include ssh task
      ansible.builtin.include_tasks: "tasks/ssh.yml"

    - name: Include git task
      ansible.builtin.include_tasks: "tasks/git.yml"

    - name: Include development task
      ansible.builtin.include_tasks: "tasks/development.yml"

    - name: Include desktop task
      ansible.builtin.include_tasks: "tasks/desktop.yml"

    - name: Include brave task
      ansible.builtin.include_tasks: "tasks/brave.yml"

    - name: Include flatpak task
      ansible.builtin.include_tasks: "tasks/flatpak.yml"
      when: (ansible_virtualization_role == "host") or (ansible_virtualization_role == "N/A")

    - name: Include i3 role
      ansible.builtin.include_role:
        name: i3
        apply:
          tags:
            - i3
      tags:
        - i3
        - never

    - name: Include gnome role
      ansible.builtin.include_role:
        name: gnome
        apply:
          tags:
            - gnome
      tags:
        - gnome

    - name: Include nvidia driver install task
      ansible.builtin.include_tasks: "tasks/nvidia.yml"
      tags:
        - nvidia
        - never

# EOF
