---

- name: install brave browser
  become: yes
  block:

    - name: install required packages for brave
      ansible.builtin.apt:
        name:
          - curl
          - apt-transport-https
        state: latest
        update_cache: yes

    - name: download brave's repo key
      ansible.builtin.get_url:
        url: "{{ brave_repo_key_url }}"
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg

    - name: brave repo ppa setting
      ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list

    - name: install brave package
      ansible.builtin.apt:
        name: brave-browser
        update_cache: yes

# end of brave block

# EOF
