---

- name: desktop packages
  become: yes
  ansible.builtin.dnf:
    name:
      - alacritty
      - bpytop
      - cava
      - flatpak
      - neofetch
    state: latest

- name: copy fonts, themes, and backgrounds
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: 'files/fonts/', dest: "{{ ansible_user_dir }}/.fonts/"}
    - {src: 'files/themes/', dest: "{{ ansible_user_dir }}/.themes/"}
    - {src: 'files/backgrounds', dest: "{{ ansible_user_dir }}/Pictures"}

- name: copy alacritty config directory
  ansible.posix.synchronize:
    src: "files/config/alacritty"
    dest: "{{ ansible_user_dir }}/.config"

- name: update font cache
  ansible.builtin.command: fc-cache -fv

# EOF
