---

- name: Common desktop packages
  become: true
  ansible.builtin.apt:
    name:
      - bpytop
      - cava
      - neofetch
      - tty-clock
    state: latest
    update_cache: yes

- name: Copy fonts, themes, and backgrounds
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: 'files/fonts/', dest: "{{ ansible_user_dir }}/.fonts/"}
    - {src: 'files/themes/', dest: "{{ ansible_user_dir }}/.themes/"}
    - {src: 'files/backgrounds', dest: "{{ ansible_user_dir }}/Pictures"}

- name: Update font cache
  ansible.builtin.command: fc-cache -fv

# EOF
