---

- name: desktop packages
  become: yes
  dnf:
    name:
      - alacritty
      - arandr
      - bpytop
      - cava
      - dunst
      - flatpak
      - i3
      - i3blocks
      - i3lock
      - i3status
      - lxappearance
      - neofetch
      - nitrogen
      - picom
      - rofi
      - xrandr
    state: latest

- name: copy fonts, themes, and backgrounds
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: 'files/fonts/', dest: "{{ ansible_user_dir }}/.fonts/"}
    - {src: 'files/themes/', dest: "{{ ansible_user_dir }}/.themes/"}
    - {src: 'files/backgrounds', dest: "{{ ansible_user_dir }}/Pictures"}

- name: copy alacritty config directory
  synchronize:
    src: "files/config/alacritty"
    dest: "{{ ansible_user_dir }}/.config"

- name: update font cache
  command: fc-cache -fv

# EOF
