---

- name: common desktop packages
  become: yes
  ansible.builtin.apt:
    name:
      - bpytop
      - cava
      - neofetch
      - tty-clock
    state: latest
    update_cache: yes

- name: copy fonts, themes, and backgrounds
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: 'files/fonts/', dest: "{{ ansible_user_dir }}/.fonts/"}
    - {src: 'files/themes/', dest: "{{ ansible_user_dir }}/.themes/"}
    - {src: 'files/backgrounds', dest: "{{ ansible_user_dir }}/Pictures"}

- name: update font cache
  ansible.builtin.command: fc-cache -fv

- name: alacritty
  block:

    - name: alacritty repo
      become: yes
      ansible.builtin.apt_repository:
        repo: 'ppa:aslatter/ppa'

    - name: install alacritty
      become: yes
      ansible.builtin.apt:
        name: alacritty
        state: latest
        update_cache: yes

    - name: copy alacritty config directory
      ansible.posix.synchronize:
        src: files/config/alacritty
        dest: "{{ ansible_user_dir }}/.config"

# end of alacritty block

# EOF
