---

- name: desktop packages
  become: yes
  dnf:
    name:
      - alacritty
      - arandr
      - bpytop
      - cava
      - dunst
      - flatpak
      - i3
      - i3blocks
      - i3lock
      - i3status
      - lxappearance
      - neofetch
      - nitrogen
      - picom
      - rofi
      - tty-clock
      - xrandr
    state: latest

- name: copy fonts, themes, and backgrounds
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: 'files/fonts/', dest: "{{ ansible_user_dir }}/.fonts/"}
    - {src: 'files/themes/', dest: "{{ ansible_user_dir }}/.themes/"}
    - {src: 'files/backgrounds', dest: "{{ ansible_user_dir }}/Pictures"}

- name: update font cache
  command: fc-cache -fv

- name: copy tiling wm configs
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: 'files/config/dunst', dest: "{{ ansible_user_dir }}/.config"}
    - {src: 'files/config/i3', dest: "{{ ansible_user_dir }}/.config"}
    - {src: 'files/config/i3status', dest: "{{ ansible_user_dir }}/.config"}
    - {src: 'files/config/picom', dest: "{{ ansible_user_dir }}/.config"}
    - {src: 'files/config/polybar', dest: "{{ ansible_user_dir }}/.config"}
    - {src: 'files/config/rofi', dest: "{{ ansible_user_dir }}/.config"}

- name: dunst confir symbolic link
  file:
    src: "{{ ansible_user_dir }}/.config/dunst/dunstrc.nord"
    dest: "{{ ansible_user_dir }}/.config/dunst/dunstrc"
    state: link

# EOF
