---

- name: install base development packages
  become: yes
  apt:
    name:
      - python3-pip
      - python3-venv
      - shellcheck

- name: install latest unstable neovim
  block:

    - name: add the neovim ppa repo
      become: yes
      apt_repository:
        repo: 'ppa:neovim-ppa/unstable'

    - name: install neovim package
      become: yes
      apt:
        name:
          - neovim
        state: latest
        update_cache: yes

    - name: create nvim config directory
      file:
        path: "{{ ansible_user_dir }}/.config/nvim"
        state: directory

    - name: deploy nvim config
      copy:
        src: files/config/nvim/init.lua
        dest: "{{ ansible_user_dir }}/.config/nvim/init.lua"

# end of neovim build block

# EOF
