---

- name: Install base development packages
  become: true
  ansible.builtin.apt:
    name:
      - python3-pip
      - python3-venv
      - shellcheck
    state: present
    update_cache: true

# EOF
