---

- name: install base development packages
  become: true
  ansible.builtin.dnf:
    name:
      - python3-pip
      - python3-virtualenv
      - shellcheck
    state: latest

- name: install lazygit
  become: true
  block:

    - name: enable lazygit copr repo
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: atim/lazygit

    - name: install lazygit package
      ansible.builtin.dnf:
        name: lazygit
        state: latest

# end of lazygit block

# EOF
