---

- name: flatpak software
  block:

    - name: add flathub flatpak repo
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: install flatpaks (personal)
      community.general.flatpak:
        name:
          - com.discordapp.Discord
          - com.dropbox.Client
          - com.spotify.Client
          - md.obsidian.Obsidian
          - org.signal.Signal
          - com.protonvpn.www
        state: present
        method: user
      when: install_environment == "personal"

    - name: install flatpaks (work)
      community.general.flatpak:
        name:
          - com.google.Chrome
          - com.slack.Slack
          - md.obsidian.Obsidian
        state: present
        method: user
      when: install_environment == "work"

# end of flatpak block

# EOF
