---

- name: Install flatpak software
  block:

    - name: Install flatpak package
      become: true
      ansible.builtin.apt:
        name: flatpak

    - name: Add flathub flatpak repo
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install flatpaks
      community.general.flatpak:
        name:
          - com.discordapp.Discord
          - com.spotify.Client
          - md.obsidian.Obsidian
          - org.signal.Signal
          - org.telegram.desktop
        state: present
        method: user

# end of flatpak block

# EOF
