---

- name: gnome things
  block:

    - name: install gnome desktop related packages
      become: yes
      apt:
        name:
          - dconf-editor
          - gnome-shell-extension-appindicator
          - gnome-shell-extension-manager
          - gnome-tweaks
        state: latest
        update_cache: yes

    - name: copy gnome shell extensions dir
      synchronize:
        src: files/extensions
        dest: "{{ ansible_user_dir }}/.local/share/gnome-shell/"

    - name: gnome workspace settings
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - {key: '/org/gnome/mutter/dynamic-workspaces', value: 'false'}
        - {key: '/org/gnome/desktop/wm/preferences/num-workspaces', value: 6}

    - name: gnome extensions settings
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - {key: '/org/gnome/shell/disabled-extensions', value: "['cosmic-dock@system76.com', 'cosmic-workspaces@system76.com']"}
#        - {key: '/org/gnome/shell/enabled-extensions', value: "['ding@rastersoft.com', 'pop-cosmic@system76.com', 'pop-shell@system76.com', 'system76-power@system76.com', 'ubuntu-appindicators@ubuntu.com', 'popx11gestures@system76.com', 'user-theme@gnome-shell-extensions.gcampax.github.com', 'launch-new-instance@gnome-shell-extensions.gcampax.github.com', 'simply.workspaces@andyrichardson.dev', 'focus@scaryrawr.github.io']"}

    - name: gnome appearance settings
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
#        - {key: '/org/gnome/desktop/interface/gtk-theme', value: "'Nordic-darker'"}
#        - {key: '/org/gnome/shell/extensions/user-theme/name', value: "'Nordic-darker'"}
        - {key: '/org/gnome/desktop/background/picture-uri', value: "'file://{{ ansible_user_dir }}/Pictures/backgrounds/harmonbetter.jpg'"}
        - {key: '/org/gnome/desktop/background/picture-uri-dark', value: "'file://{{ ansible_user_dir }}/Pictures/backgrounds/harmonbetter.jpg'"}

    - name: gnome keybindings
      dconf:
        key: "{{ item.key }}"
        value: "{{ item.value }}"
      loop:
        - {key: '/org/gnome/desktop/wm/keybindings/switch-to-workspace-1', value: "['<Super>1']"}
        - {key: '/org/gnome/desktop/wm/keybindings/switch-to-workspace-2', value: "['<Super>2']"}
        - {key: '/org/gnome/desktop/wm/keybindings/switch-to-workspace-3', value: "['<Super>3']"}
        - {key: '/org/gnome/desktop/wm/keybindings/switch-to-workspace-4', value: "['<Super>4']"}
        - {key: '/org/gnome/desktop/wm/keybindings/switch-to-workspace-5', value: "['<Super>5']"}
        - {key: '/org/gnome/desktop/wm/keybindings/switch-to-workspace-6', value: "['<Super>6']"}
        - {key: '/org/gnome/desktop/wm/keybindings/switch-to-workspace-left', value: "['<Control><Alt>Left']"}
        - {key: '/org/gnome/desktop/wm/keybindings/switch-to-workspace-right', value: "['<Control><Alt>Right']"}

  tags: gnome

# end of gnome things block

# EOF
