---

- name: install desktop packages
  become: yes
  block:

    - name: common desktop packages
      apt:
        name:
          - arandr
          - dunst
          - lxappearance
          - nitrogen
          - picom
          - rofi
        state: latest
        update_cache: yes

    - name: i3
      block:

        - name: add regolith apt repo key
          get_url:
            url: "{{ regolith_repo_key_url }}"
            dest: /etc/apt/trusted.gpg.d/regolith.asc
            mode: '0644'
            force: true

        - name: add regolith repo
          apt_repository:
            repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/regolith.asc] https://regolith-desktop.org/release-ubuntu-{{ ansible_distribution_release }}-amd64 {{ ansible_distribution_release }} main"
            state: present   

        - name: install i3-gaps related packages
          apt:
            name:
              - i3-gaps
              - i3lock
              - i3lock-fancy
            state: latest
            update_cache: yes

    # end of i3 block

# end of package install block

- name: copy dunst config directory
  synchronize:
    src: files/config/dunst
    dest: "{{ ansible_user_dir }}/.config"

- name: copy i3 config directory
  synchronize:
    src: files/config/i3
    dest: "{{ ansible_user_dir }}/.config"

- name: copy i3status config directory
  synchronize:
    src: files/config/i3status
    dest: "{{ ansible_user_dir }}/.config"

- name: copy picom config directory
  synchronize:
    src: files/config/picom
    dest: "{{ ansible_user_dir }}/.config"

- name: copy polybar config directory
  synchronize:
    src: files/config/polybar
    dest: "{{ ansible_user_dir }}/.config"

- name: copy rofi config directory
  synchronize:
    src: files/config/rofi
    dest: "{{ ansible_user_dir }}/.config"

- name: deploy configs
  block:

    - name: deploy alacritty config template
      template:
        src: config/alacritty/alacritty.yml.j2
        dest: "{{ ansible_user_dir }}/.config/alacritty/alacritty.yml"

    - name: deploy i3 config template
      template:
        src: config/i3/config.j2
        dest: "{{ ansible_user_dir }}/.config/i3/config"

    - name: deploy rofi config template
      template:
        src: config/rofi/config.rasi.j2
        dest: "{{ ansible_user_dir }}/.config/rofi/config.rasi"

    - name: dunst symbolic link
      file:
        src: "{{ ansible_user_dir }}/.config/dunst/dunstrc.{{ theme }}"
        dest: "{{ ansible_user_dir }}/.config/dunst/dunstrc"
        state: link

  tags: changetheme

# end of configs block

# EOF
