---

- name: do nvidia driver tasks
  become: true
  block:

  - name: install nvidia driver related packages
    ansible.builtin.dnf:
      name:
        - kernel-devel
        - akmod-nvidia
        - xorg-x11-drv-nvidia-cuda
      state: latest

  - name: enable nvidia hibernate service
    ansible.builtin.service:
      name: nvidia-hibernate.service
      enabled: yes

  - name: enable nvidia suspend service
    ansible.builtin.service: 
      name: nvidia-suspend.service
      enabled: yes

  - name: enable nvidia resume service
    ansible.builtin.service:
      name: nvidia-resume.service
      enabled: yes

  tags: nvidia

# end of nvidia driver tasks block

# EOF
