---

- name: Install base packages block
  become: true
  block:

    - name: Add rpmfusion free gpg key
      ansible.builtin.rpm_key:
        state: present
        key: "{{ rpmfusion_free_key }}"

    - name: Add rpmfusion nonfree gpg key
      ansible.builtin.rpm_key:
        state: present
        key: "{{ rpmfusion_nonfree_key }}"

    - name: Install rpmfusion free repository
      ansible.builtin.dnf:
        name: "{{ rpmfusion_free_repo }}"
        state: present

    - name: Install rpmfusion nonfree repository
      ansible.builtin.dnf:
        name: "{{ rpmfusion_nonfree_repo }}"
        state: present

    - name: DNF conf changes
      ansible.builtin.blockinfile:
        path: /etc/dnf/dnf.conf
        block: |
          max_parallel_downloads=10
          fastestmirror=True
        backup: true

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install base packages
      ansible.builtin.dnf:
        name:
          - ansible
          - bpytop
          - curl
          - '@Development Tools'
          - dnf-plugins-core
          - fastfetch
          - git
          - kernel-devel
          - nmap
          - traceroute
          - tree
          - util-linux-user
        state: present

    - name: Install multimedia packages
      ansible.builtin.dnf:
        name: '@Multimedia'
        allowerasing: true
        state: present

# End of base packages block

# EOF
