---

- name: Install base packages block
  become: true
  block:

    - name: Add rpmfusion free gpg key
      ansible.builtin.rpm_key:
        state: present
        key: "{{ rpmfusion_free_key }}"

    - name: Add rpmfusion nonfree gpg key
      ansible.builtin.rpm_key:
        state: present
        key: "{{ rpmfusion_nonfree_key }}"

    - name: Install rpmfusion free repository
      ansible.builtin.dnf:
        name: "{{ rpmfusion_free_repo }}"
        state: present

    - name: Install rpmfusion nonfree repository
      ansible.builtin.dnf:
        name: "{{ rpmfusion_nonfree_repo }}"
        state: present

    - name: DNF conf changes
      ansible.builtin.blockinfile:
        path: /etc/dnf/dnf.conf
        block: |
          max_parallel_downloads=10
          fastestmirror=True
        backup: true

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install base packages
      ansible.builtin.dnf:
        name:
          - ansible
          - bpytop
          - curl
          - '@Development Tools'
          - dnf-plugins-core
          - fastfetch
          - git
          - kernel-devel
          - nmap
          - traceroute
          - tree
          - util-linux-user
        state: present

    - name: Install multimedia packages
      ansible.builtin.dnf:
        name: '@Multimedia'
        allowerasing: true
        state: present

    - name: Install and configure neovim
      block:

        - name: Install neovim
          ansible.builtin.dnf:
            name: neovim
            state: present

        - name: Make sure nvim share directory is absent
          ansible.builtin.file:
            path: "{{ ansible_user_dir }}/.local/share/nvim"
            state: absent

        - name: Make sure nvim config directory is absent
          ansible.builtin.file:
            path: "{{ ansible_user_dir }}/.config/nvim"
            state: absent

        - name: Copy neovim config directory
          ansible.posix.synchronize:
            src: "files/config/nvim"
            dest: "{{ ansible_user_dir }}/.config"

    # end of neovim install and config block

    - name: Install sublime text editor
      block:

        - name: Install the gpg key
          ansible.builtin.rpm_key:
            state: present
            key: https://download.sublimetext.com/sublimehq-rpm-pub.gpg

        - name: Add sublime repo
          ansible.builtin.get_url:
            url: https://download.sublimetext.com/rpm/stable/x86_64/sublime-text.repo
            dest: /etc/yum.repos.d/sublime-text.repo

        - name: Install sublime-text package
          ansible.builtin.dnf:
            name: sublime-text
            state: present

    # end of sublime-text install block

    - name: Install tailscale
      block:

        - name: Install tailscale repo
          ansible.builtin.get_url:
            url: https://pkgs.tailscale.com/stable/fedora/tailscale.repo
            dest: /etc/yum.repos.d/tailscale.repo

        - name: Install tailscale
          ansible.builtin.dnf:
            name: tailscale
            state: present

        - name: Enable tailscale service
          ansible.builtin.service:
            name: tailscaled
            enabled: true

        - name: Start tailscale service
          ansible.builtin.service:
            name: tailscaled
            state: started

    # end of tailscale block

# End of base packages block

# EOF
