---

- name: Update all packages
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: Install base packages
  become: true
  ansible.builtin.apt:
    name:
      - bind9-dnsutils
      - bpytop
      - curl
      - neofetch
      - nmap
      - os-prober
      - software-properties-common
      - traceroute
      - tree
      - unzip
      - zsh
    state: present
    update_cache: true

- name: Install latest unstable neovim
  block:

    - name: Add the neovim ppa repo
      become: true
      ansible.builtin.apt_repository:
        repo: 'ppa:neovim-ppa/unstable'

    - name: Install neovim package
      become: true
      ansible.builtin.apt:
        name:
          - neovim
        state: present
        update_cache: true

    - name: Make sure nvim share directory is absent
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.local/share/nvim"
        state: absent

    - name: Make sure nvim config directory is absent
      ansible.builtin.file:
        path: "{{ ansible_user_dir }}/.config/nvim"
        state: absent

    - name: Copy neovim config directory
      ansible.posix.synchronize:
        src: files/config/nvim
        dest: "{{ ansible_user_dir }}/.config"

# end of neovim block

- name: Install tailscale
  become: true
  block:

    - name: Download tailscale keyring
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
        dest: /usr/share/keyrings/tailscale-archive-keyring.gpg

    - name: Download tailscale repo file
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list
        dest: /etc/apt/sources.list.d/tailscale.list

    - name: Install tailscale package
      ansible.builtin.apt:
        name: tailscale
        state: present
        update_cache: true

# end of tailscale block

# EOF
