---

- name: Update all packages
  become: true
  apt:
    name: "*"
    state: latest
    update_cache: true

- name: Install base packages
  become: true
  apt:
    name:
      - curl
      - flatpak
      - heif-gdk-pixbuf
      - krita
      - nmap
      - os-prober
      - shellcheck
      - software-properties-common
      - traceroute
      - tree
      - zsh
    state: present
    update_cache: true

- name: Install latest unstable neovim
  block:

    - name: Add the neovim ppa repo
      become: true
      apt_repository:
        repo: 'ppa:neovim-ppa/unstable'

    - name: Install neovim package
      become: true
      apt:
        name:
          - neovim
        state: present
        update_cache: true

    - name: Symlink vim to nvim
      become: true
      file:
        src: /usr/bin/nvim
        dest: /usr/local/bin/vim
        state: link

    - name: Make sure nvim share directory is absent
      file:
        path: "{{ ansible_user_dir }}/.local/share/nvim"
        state: absent

    - name: Make sure nvim config directory is absent
      file:
        path: "{{ ansible_user_dir }}/.config/nvim"
        state: absent

    - name: Copy neovim config directory
      synchronize:
        src: files/config/nvim
        dest: "{{ ansible_user_dir }}/.config"

# end of neovim block

# EOF
