---

- name: set up ssh environment
  block:

    - name: verify/create the .ssh directory 
      ansible.builtin.file:
        dest: "{{ ssh_dir }}"
        mode: 0700
        state: directory

    - name: copy ssh keys
      ansible.builtin.copy:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
        mode: "{{ item.mode }}"
      loop:
        - {src: "files/ssh/{{ ssh_key }}-{{ install_environment }}", dest: "{{ ssh_dir }}/{{ ssh_key }}", mode: '0600'}
        - {src: "files/ssh/{{ ssh_key }}-{{ install_environment }}.pub", dest: "{{ ssh_dir }}/{{ ssh_key }}.pub", mode: '0644'}

    - name: authorize personal ssh keys
      ansible.posix.authorized_key:
        user: "{{ ansible_user_id }}"
        state: present
        key: "files/ssh/{{ ssh_key }}.pub"
        key: "{{ lookup('file', lookup('env','HOME') + '/.ssh/id_ed25519.pub') }}"

    - name: deploy ssh config
      ansible.builtin.copy:
        src: "files/ssh/config"
        dest: "{{ ssh_dir }}/config"
        mode: 0600

# end of ssh block

# EOF
