---

- name: Install tailscale
  block:

    - name: Install tailscale repo
      ansible.builtin.get_url:
        url: https://pkgs.tailscale.com/stable/fedora/tailscale.repo
        dest: /etc/yum.repos.d/tailscale.repo

    - name: Install tailscale
      ansible.builtin.dnf:
        name: tailscale
        state: present

    - name: Enable tailscale service
      ansible.builtin.service:
        name: tailscaled
        enabled: true

    - name: Start tailscale service
      ansible.builtin.service:
        name: tailscaled
        state: started

# End of tailscale block

# EOF
