---

- name: Get zsh happening
  block:

    - name: Set zsh as shell
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh

    - name: Clone oh-my-zsh repo
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "{{ ansible_user_dir }}/.oh-my-zsh"
        depth: 1

    - name: Copy custom oxide oh-my-zsh theme
      ansible.builtin.copy:
        src: "files/oh-my-zsh-themes/oxide.zsh-theme"
        dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes/"

    - name: Install .zshrc
      ansible.builtin.copy:
        src: "files/zshrc"
        dest: "{{ ansible_user_dir }}/.zshrc"
        backup: yes

  tags: zsh

# End of zsh block

# EOF
