---

- name: get zsh happening
  block:

    - name: set zsh as shell
      become: true
      ansible.builtin.user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh

    - name: oh-my-zsh
      ansible.builtin.git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "{{ ansible_user_dir }}/.oh-my-zsh"
        depth: 1

    - name: .zshrc
      ansible.builtin.copy:
        src: "files/zshrc"
        dest: "{{ ansible_user_dir }}/.zshrc" 
        backup: yes

    - name: copy custom zsh themes
      ansible.builtin.copy:
        src: "files/oxide.zsh-theme"
        dest: "{{ ansible_user_dir }}/.oh-my-zsh/custom/themes"

  tags: zsh

# End of zsh block

# EOF
