---

- name: get zsh happening
  block:

    - name: set zsh as shell
      become: yes
      user:
        name: "{{ ansible_user_id }}"
        shell: /usr/bin/zsh

    - name: oh-my-zsh
      git:
        repo: https://github.com/ohmyzsh/ohmyzsh.git
        dest: "{{ ansible_user_dir }}/.oh-my-zsh"
        depth: 1

    - name: .zshrc
      copy:
        src: "files/zshrc"
        dest: "{{ ansible_user_dir}}/.zshrc" 
        backup: yes

# End of zsh block

# EOF
