---

- name: Install flatpak software
  tags: flatpak
  block:

    - name: Install flatpak package
      become: true
      ansible.builtin.package:
        name: flatpak
        state: present

    - name: Add flathub flatpak repo
      community.general.flatpak_remote:
        name: flathub
        state: present
        flatpakrepo_url: https://flathub.org/repo/flathub.flatpakrepo
        method: user

    - name: Install flatpaks
      community.general.flatpak:
        name: "{{ item }}"
        state: present
        method: user
      loop: "{{ flatpak_packages }}"

# end of flatpak block

# EOF
