# alacritty config
#
# Written by: Corey Reppond
#
# reppocs@gmail.com

env:
  TERM: xterm-256color

window:
  title: alacritty
  padding:
    x: 10
    y: 10
  opacity: 1.0

font:
  normal:
    family: JetBrainsMono Nerd Font
    style: Regular
  bold:
    family: JetBrainsMono Nerd Font
    style: Bold
  italic:
    family: JetBrainsMono Nerd Font
    style: Italic
  bold_italic:
    family: JetBrainsMono Nerd Font
    style: Bold Italic
  size: 10.0

# Pick a theme (uncomment)
import:
  - ~/.config/alacritty/themes/onedark2.yml
