---

- name: copy i3-related config directories
  synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: 'files/dunst', dest: "{{ ansible_user_dir }}/.config"}
    - {src: 'files/i3', dest: "{{ ansible_user_dir }}/.config"}
    - {src: 'files/i3status', dest: "{{ ansible_user_dir }}/.config"}
    - {src: 'files/picom', dest: "{{ ansible_user_dir }}/.config"}
    - {src: 'files/polybar', dest: "{{ ansible_user_dir }}/.config"}
    - {src: 'files/rofi', dest: "{{ ansible_user_dir }}/.config"}

- name: make sure that the dunstrc file/link is gone
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.config/dunst/dunstrc"
    state: absent

- name: dunstrc config file theme symbolic links
  ansible.builtin.file:
    src: "{{ ansible_user_dir }}/.config/dunst/dunstrc.{{ theme }}"
    dest: "{{ ansible_user_dir }}/.config/dunst/dunstrc"
    state: link

# EOF
