---

- name: i3 desktop stuff
  block:

    - name: install i3-related packages
      become: yes
      block:

        - name: common desktop packages
          apt:
            name:
              - arandr
              - dunst
              - lxappearance
              - nitrogen
              - picom
              - rofi
            state: latest
            update_cache: yes

        - name: install i3
          block:

            - name: add regolith apt repo key
              get_url:
                url: "{{ regolith_repo_key_url }}"
                dest: /etc/apt/trusted.gpg.d/regolith.asc
                mode: '0644'
                force: true

            - name: add regolith repo
              apt_repository:
                repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/regolith.asc] https://regolith-desktop.org/release-ubuntu-{{ ansible_distribution_release }}-amd64 {{ ansible_distribution_release }} main"
                state: present   

            - name: install i3-gaps related packages
              apt:
                name:
                  - i3-gaps
                  - i3lock
                  - i3lock-fancy
                state: latest
                update_cache: yes

        # end of install i3 block

    # end of install i3-related packages block

    - name: copy i3-related config directories
      synchronize:
        src: "{{ item.src }}"
        dest: "{{ item.dest }}"
      loop:
        - {src: 'files/config/dunst', dest: "{{ ansible_user_dir }}/.config"}
        - {src: 'files/config/i3', dest: "{{ ansible_user_dir }}/.config"}
        - {src: 'files/config/i3status', dest: "{{ ansible_user_dir }}/.config"}
        - {src: 'files/config/picom', dest: "{{ ansible_user_dir }}/.config"}
        - {src: 'files/config/polybar', dest: "{{ ansible_user_dir }}/.config"}
        - {src: 'files/config/rofi', dest: "{{ ansible_user_dir }}/.config"}

# end of i3 desktop stuff block

# EOF
