---
# tasks file for i3

- name: include i3 packages task
  include_tasks: "packages-{{ ansible_distribution }}.yml"

- name: include i3 configs task
  include_tasks: "configs.yml"

- name: make the system do nothing when the laptop lid is closed
  lineinfile:
    path: /etc/systemd/logind.conf
    line: HandleLidSwitchExternalPower=ignore    
    insertafter: EOF
    state: present
    backup: true
 
# EOF
