---
# tasks file for i3

- name: Include i3 packages task
  ansible.builtin.include_tasks: "packages-{{ ansible_os_family }}.yml"

- name: Include i3 configs task
  ansible.builtin.include_tasks: "configs.yml"

- name: Make the system do nothing when the laptop lid is closed
  become: true
  ansible.builtin.lineinfile:
    path: /etc/systemd/logind.conf
    line: HandleLidSwitchExternalPower=ignore
    insertafter: EOF
    state: present
    backup: true

# EOF
