---

- name: i3 desktop stuff
  block:

    - name: install i3-related packages
      become: true
      block:

        - name: common desktop packages
          ansible.builtin.apt:
            name:
              - arandr
              - dunst
              - lxappearance
              - lxrandr
              - nitrogen
              - pcmanfm
              - picom
              - polybar
              - rofi
            state: latest
            update_cache: yes

        - name: alacritty
          block:

            - name: alacritty repo
              ansible.builtin.apt_repository:
                repo: 'ppa:aslatter/ppa'

            - name: install alacritty
              ansible.builtin.apt:
                name: alacritty
                state: latest
                update_cache: yes

        # end of alacritty block

        - name: install i3
          block:

            - name: add regolith apt repo key
              ansible.builtin.get_url:
                url: "{{ regolith_repo_key_url }}"
                dest: /etc/apt/trusted.gpg.d/regolith.asc
                mode: '0644'
                force: true

            - name: add regolith repo
              ansible.builtin.apt_repository:
                repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/regolith.asc] https://regolith-desktop.org/release-ubuntu-{{ ansible_distribution_release }}-amd64 {{ ansible_distribution_release }} main"
                state: present   

            - name: install i3-gaps related packages
              ansible.builtin.apt:
                name:
                  - i3-gaps
                  - i3lock
                  - i3lock-fancy
                state: latest
                update_cache: yes

        # end of install i3 block

    # end of install i3-related packages block

# end of i3 desktop stuff block

# EOF
