---

- name: i3 desktop stuff
  block:

    - name: install i3-related packages
      become: true
      block:

        - name: common desktop packages
          ansible.builtin.dnf:
            name:
              - alacritty
              - arandr
              - dunst
              - lxappearance
              - lxrandr
              - nitrogen
              - picom
              - rofi
              - polybar
              - xrandr
              - xset
            state: latest

        - name: desktop environment substitute packages
          ansible.builtin.dnf:
            name:
              - blueman
              - pcmanfm
            state: latest

        - name: i3 packages
          ansible.builtin.dnf:
            name:
              - i3
              - i3blocks
              - i3lock
              - i3status
            state: latest

# end of i3 desktop stuff block

# EOF
