---

- name: Install and configure i3 desktop stuff
  block:

    - name: Install i3-related packages
      become: true
      block:

        - name: Install common desktop packages
          ansible.builtin.dnf:
            name:
              - arandr
              - dunst
              - lxappearance
              - lxrandr
              - nitrogen
              - picom
              - rofi
              - polybar
              - xrandr
              - xset
            state: present

        - name: Install desktop environment substitute packages
          ansible.builtin.dnf:
            name:
              - blueman
              - pcmanfm
            state: present

        - name: Install i3 packages
          ansible.builtin.dnf:
            name:
              - i3
              - i3blocks
              - i3lock
              - i3status
            state: present

# end of i3 desktop stuff block

# EOF
