---

- name: Install and configure i3 desktop
  block:

    - name: Install i3-related packages
      become: true
      block:

        - name: Common desktop packages
          ansible.builtin.apt:
            name:
              - arandr
              - dunst
              - lxappearance
              - lxrandr
              - nitrogen
              - pcmanfm
              - picom
              - polybar
              - rofi
            state: present
            update_cache: yes

        - name: Install i3
          block:

            - name: Add regolith apt repo key
              ansible.builtin.get_url:
                url: "{{ regolith_repo_key_url }}"
                dest: /etc/apt/trusted.gpg.d/regolith.asc
                mode: '0644'
                force: true

            - name: Add regolith repo
              ansible.builtin.apt_repository:
                repo: "deb [arch=amd64 signed-by=/etc/apt/trusted.gpg.d/regolith.asc] https://regolith-desktop.org/release-ubuntu-{{ ansible_distribution_release }}-amd64 {{ ansible_distribution_release }} main"
                state: present

            - name: Install i3-gaps related packages
              ansible.builtin.apt:
                name:
                  - i3-gaps
                  - i3lock
                  - i3lock-fancy
                state: present
                update_cache: yes

        # end of install i3 block

    # end of install i3-related packages block

# end of i3 desktop stuff block

# EOF
