---

- name: Install brave browser
  become: true
  block:

    - name: Install required packages for brave
      ansible.builtin.apt:
        name:
          - curl
          - apt-transport-https
        state: present
        update_cache: true

    - name: Download brave's repo key
      ansible.builtin.get_url:
        url: "{{ brave_repo_key_url }}"
        dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
        mode: '0644'

#    - name: Brave repo ppa setting
#      ansible.builtin.shell: echo "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main" | tee /etc/apt/sources.list.d/brave-browser-release.list

    - name: Set brave repo ppa
      ansible.builtin.apt_repository:
        repo: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
        filename: brave-browser-release
        state: present

    - name: Install brave package
      ansible.builtin.apt:
        name: brave-browser
        update_cache: true

# end of brave block

# EOF
