---

- name: Install brave browser
  become: true
  block:

    - name: Install required packages for brave
      ansible.builtin.dnf:
        name: dnf-plugins-core
        state: present

    - name: Add brave repo
      ansible.builtin.get_url:
        url: https://brave-browser-rpm-release.s3.brave.com/brave-browser.repo
        dest: /etc/yum.repos.d/brave-browser.repo

    - name: Download brave's repo key
      ansible.builtin.rpm_key:
        state: present
        key: https://brave-browser-rpm-release.s3.brave.com/brave-core.asc

    - name: Install brave package
      ansible.builtin.dnf:
        name:
          - brave-browser
          - brave-keyring
        state: present

  tags:
    - brave

# end of brave block

# EOF
