---

- name: Install gnome base packages
  become: true
  ansible.builtin.dnf:
    name:
      - gnome-extensions-app
      - gnome-tweaks
    state: present

- name: Install gnome extensions
  become: true
  ansible.builtin.dnf:
    name:
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-apps-menu
      - gnome-shell-extension-auto-move-windows
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-dash-to-dock
      - gnome-shell-extension-dash-to-panel
      - gnome-shell-extension-just-perfection
      - gnome-shell-extension-launch-new-instance
      - gnome-shell-extension-places-menu
      - gnome-shell-extension-pop-shell
      - gnome-shell-extension-user-theme
    state: present

# EOF
