---

- name: Install gnome base packages
  become: true
  ansible.builtin.apt:
    name:
      - dconf-editor
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-manager
      - gnome-tweaks
    state: present
    update_cache: true

# EOF
