---

- name: Change gnome workspace settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - {key: "/org/gnome/mutter/dynamic-workspaces", value: "false"}
    - {key: "/org/gnome/desktop/wm/preferences/num-workspaces", value: 6}

- name: Change gnome appearance settings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - {key: "/org/gnome/desktop/background/picture-uri", value: "'file://{{ ansible_user_dir }}/Pictures/backgrounds/slothlife.png'"}
    - {key: '/org/gnome/desktop/background/picture-uri-dark', value: "'file://{{ ansible_user_dir }}/Pictures/backgrounds/slothlife.png'"}

- name: Change gnome keybindings
  community.general.dconf:
    key: "{{ item.key }}"
    value: "{{ item.value }}"
  loop:
    - {key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-left", value: "['<Control><Alt>Left']"}
    - {key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-right", value: "['<Control><Alt>Right']"}
    - {key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-1", value: "['<Super>1']"}
    - {key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-2", value: "['<Super>2']"}
    - {key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-3", value: "['<Super>3']"}
    - {key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-4", value: "['<Super>4']"}
    - {key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-5", value: "['<Super>5']"}
    - {key: "/org/gnome/desktop/wm/keybindings/switch-to-workspace-6", value: "['<Super>6']"}


- name: Change gnome-terminal settings
  block:

    - name: Disable gnome-terminal bell
      community.general.dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/audible-bell"
        value: "false"

    - name: Set gnome-terminal font
      community.general.dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/font"
        value: "'JetBrainsMono Nerd Font 12'"

    - name: Change "use custom font" setting in gnome-terminal
      community.general.dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-system-font"
        value: "false"

    - name: Set gnome-terminal transparency
      community.general.dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/use-transparent-background"
        value: "true"

    - name: Set gnome-terminal transparency percentage
      community.general.dconf:
        key: "/org/gnome/terminal/legacy/profiles:/:b1dcc9dd-5262-4d8d-a863-c897e6d979b9/background-transparency-percent"
        value: 5

# end of gnome-terminal settings block

- name: Disable gnome extensions
  community.general.dconf:
    key: "/org/gnome/shell/disabled-extensions"
    value: "['background-logo@fedorahosted.org']"

- name: Enable gnome extensions
  community.general.dconf:
    key: "/org/gnome/shell/enabled-extensions"
    value: "['appindicatorsupport@rgcjonas.gmail.com', 'auto-move-windows@gnome-shell-extensions.gcampax.github.com', 'launch-new-instance@gnome-shell-extensions.gcampax.github.com', 'pop-shell@system76.com', 'user-theme@gnome-shell-extensions.gcampax.github.com']"

- name: Set clock format to 12h
  community.general.dconf:
    key: "/org/gnome/desktop/interface/clock-format"
    value: "'12h'"

- name: Set color scheme to dark
  community.general.dconf:
    key: "/org/gnome/desktop/interface/color-scheme"
    value: "'prefer-dark'"

# EOF
