---

- name: Configure git
  block:

    - name: Create and verify git repo directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ ansible_user_id }}"
        group: "{{ ansible_user_gid }}"
        mode: "0755"
      loop:
        - "{{ git_dir }}/personal"
        - "{{ git_dir }}/public"

    - name: Copy git config file
      ansible.builtin.copy:
        src: "files/gitconfig"
        dest: "{{ ansible_user_dir }}/.gitconfig"
        mode: "0644"
        backup: true
  tags:
    - git

# EOF
