# https://gist.github.com/r-darwish

colors:
  primary:
    background: '0x1a1b26'
    foreground: '0xa9b1d6'
    bright_foreground: '#ffffff'
  cursor:
    text: CellBackground
    cursor: CellForeground
  vi_mode_cursor:
    text: CellBackground
    cursor: CellForeground
  search:
    matches:
      foreground: '#44475a'
      background: '#50fa7b'
    focused_match:
      foreground: '#44475a'
      background: '#ffb86c'
  footer_bar:
    background: '#282a36'
    foreground: '#f8f8f2'
  hints:
    start:
      foreground: '#282a36'
      background: '#f1fa8c'
    end:
      foreground: '#f1fa8c'
      background: '#282a36'
  line_indicator:
    foreground: None
    background: None
  selection:
    text: CellForeground
    background: '#44475a'
  normal:
    black: '0x32344a'
    red: '0xf7768e'
    green: '0x9ece6a'
    yellow: '0xe0af68'
    blue: '0x7aa2f7'
    magenta: '0xad8ee6'
    cyan: '0x449dab'
    white: '0x787c99'
  bright:
    black: '0x444b6a'
    red: '0xff7a93'
    green: '0xb9f27c'
    yellow: '0xff9e64'
    blue: '0x7da6ff'
    magenta: '0xbb9af7'
    cyan: '0x0db9d7'
    white: '0xacb0d0'
