---

- name: Update all packages
  become: true
  ansible.builtin.apt:
    name: "*"
    state: latest
    update_cache: true

- name: Install base packages
  become: true
  ansible.builtin.apt:
    name:
      - bind9-dnsutils
      - bpytop
      - curl
      - neofetch
      - nmap
      - os-prober
      - software-properties-common
      - traceroute
      - tree
      - unzip
      - zsh
    state: present
    update_cache: true

# EOF
