# Kitty Config
#
# Written by: Corey Reppond <reppocs@gmail.com>

# theme
include themes/nord.conf

# Fonts
font_family           JetBrainsMono Nerd Font
bold_font             JetBrains Mono Bold Nerd Font Complete
italic_font           JetBrains Mono Italic Nerd Font Complete
bold_italic_font      JetBrains Mono Bold Italic Nerd Font Complete

font_size             10

# how far to scroll back
scrollback_lines 5000

# window stuff
window_padding_width 5
