---

- name: Common desktop packages
  become: true
  ansible.builtin.apt:
    name:
      - heif-gdk-pixbuf
      - krita
    state: present
    update_cache: true

- name: Copy fonts, themes, and backgrounds
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: 'files/fonts/', dest: "{{ ansible_facts['user_dir'] }}/.fonts/"}
    - {src: 'files/themes/', dest: "{{ ansible_facts['user_dir'] }}/.themes/"}
    - {src: 'files/backgrounds', dest: "{{ ansible_facts['user_dir'] }}/Pictures"}

- name: Update font cache
  ansible.builtin.command:
    cmd: fc-cache -f
  changed_when: true

# EOF
