---

- name: Common desktop packages
  become: true
  ansible.builtin.apt:
    name:
      - cava
      - heif-gdk-pixbuf
      - kitty
      - krita
      - tty-clock
    state: present
    update_cache: true

- name: Copy kitty terminal config
  ansible.posix.synchronize:
    src: "files/config/kitty"
    dest: "{{ ansible_user_dir }}/.config/"

- name: Copy fonts, themes, and backgrounds
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: 'files/fonts/', dest: "{{ ansible_user_dir }}/.fonts/"}
    - {src: 'files/themes/', dest: "{{ ansible_user_dir }}/.themes/"}
    - {src: 'files/backgrounds', dest: "{{ ansible_user_dir }}/Pictures"}

- name: Update font cache
  ansible.builtin.command:
    cmd: fc-cache -f
  changed_when: true

# EOF
