---

- name: Common desktop packages
  become: true
  ansible.builtin.apt:
    name:
      - cava
      - heif-gdk-pixbuf
      - kitty
      - krita
      - tty-clock
    state: present
    update_cache: true

- name: Install ghostty terminal
  become: true
  block:

    - name: Add ghostty terminal PPA
      ansible.builtin.apt_repository:
        repo: ppa:mkasberg/ghostty-ubuntu
        state: present
        update_cache: true

    - name: Install ghostty terminal
      ansible.builtin.apt:
        name: ghostty
        state: present

    - name: Copy ghostty terminal config
      ansible.posix.synchronize:
        src: "files/config/ghostty"
        dest: "{{ ansible_facts['user_dir'] }}/.config/"

# End of ghostty install block

- name: Copy kitty terminal config
  ansible.posix.synchronize:
    src: "files/config/kitty"
    dest: "{{ ansible_facts['user_dir'] }}/.config/"

- name: Copy fonts, themes, and backgrounds
  ansible.posix.synchronize:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  loop:
    - {src: 'files/fonts/', dest: "{{ ansible_facts['user_dir'] }}/.fonts/"}
    - {src: 'files/themes/', dest: "{{ ansible_facts['user_dir'] }}/.themes/"}
    - {src: 'files/backgrounds', dest: "{{ ansible_facts['user_dir'] }}/Pictures"}

- name: Update font cache
  ansible.builtin.command:
    cmd: fc-cache -f
  changed_when: true

# EOF
