---

- name: Update all packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe

- name: Install base packages
  become: true
  ansible.builtin.apt:
    name:
      - atuin
      - bat
      - bind9-dnsutils
      - bpytop
      - curl
      - fastfetch
      - fish
      - nmap
      - os-prober
      - software-properties-common
      - traceroute
      - tree
      - unzip
      - zsh
    state: present
    update_cache: true

- name: Create symlink ~/.local/bin/bat -> /usr/bin/batcat
  ansible.builtin.file:
    src: /usr/bin/batcat
    dest: "{{ ansible_facts['env']['HOME'] }}/.local/bin/bat"
    state: link
