---
- name: Install base packages block
  become: true
  block:
    - name: Install rpmfusion free repository
      ansible.builtin.dnf:
        name: "{{ rpmfusion_free_repo }}"
        state: present
        disable_gpg_check: true

    - name: Install rpmfusion nonfree repository
      ansible.builtin.dnf:
        name: "{{ rpmfusion_nonfree_repo }}"
        state: present
        disable_gpg_check: true

    - name: DNF conf changes
      ansible.builtin.blockinfile:
        path: /etc/dnf/dnf.conf
        block: |
          max_parallel_downloads=10
          fastestmirror=True
        backup: true

    - name: Upgrade all packages
      ansible.builtin.dnf:
        name: "*"
        state: latest

    - name: Install base packages
      ansible.builtin.dnf:
        name:
          - ansible
          - btop
          - curl
          - "@Development Tools"
          - dnf-plugins-core
          - dnf-utils
          - fastfetch
          - fzf
          - git
          - git-delta
          - kernel-devel
          - nmap
          - traceroute
          - tree
          - util-linux-user
        state: present
# End of base packages block

# EOF
