---

- name: Update all packages
  become: true
  ansible.builtin.apt:
    update_cache: true
    upgrade: safe

- name: Install base packages
  become: true
  ansible.builtin.apt:
    name:
      - bat
      - bind9-dnsutils
      - bpytop
      - curl
      - fastfetch
      - fish
      - nmap
      - os-prober
      - software-properties-common
      - traceroute
      - tree
      - unzip
      - zsh
    state: present
    update_cache: true

# EOF
