---
- name: Install starship prompt Fedora
  become: true
  when: ansible_os_family == "RedHat"
  block:
    - name: Install starship copr repo
      become: true
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: atim/starship

    - name: Install starship
      become: true
      ansible.builtin.dnf:
        name: starship
        state: present

# End of Fedora starship block

- name: Install starship prompt Ubuntu
  become: true
  community.general.snap:
    name: starship
    channel: edge
  when: ansible_os_family == "Debian"

- name: Copy bash config
  ansible.builtin.copy:
    src: "files/bashrc"
    dest: "{{ ansible_user_dir }}/.bashrc"
    mode: "0644"
# EOF
