---

- name: Install terminal packages (Fedora)
  become: true
  when: ansible_facts["os_family"] == "RedHat"
  ansible.builtin.dnf:
    name:
      - atuin
      - bat
      - btop
      - fastfetch
      - fzf
      - cava
      - fish
      - kitty
      - krita
      - tree
      - zsh
    state: present
  tags: terminal

- name: Install terminal packages (Ubuntu)
  become: true
  when: ansible_facts["os_family"] == "Debian"
  ansible.builtin.apt:
    name:
      - cava
      - ghostty
      - kitty
      - tty-clock
    state: present
    update_cache: true
  tags: terminal

- name: Install ghostty terminal (Fedora)
  become: true
  when: ansible_facts["os_family"] == "RedHat"
  block:
    - name: Install ghostty terminal copr repo
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: scottames/ghostty

    - name: Install ghostty terminal
      ansible.builtin.dnf:
        name: ghostty
        state: present

    - name: Copy ghostty terminal config
      ansible.posix.synchronize:
        src: "files/config/ghostty"
        dest: "{{ ansible_facts['user_dir'] }}/.config/"
  tags: terminal

# End of Fedora ghostty install block

- name: Install starship prompt (Fedora)
  become: true
  when: ansible_facts["os_family"] == "RedHat"
  block:
    - name: Install starship copr repo
      become: true
      community.general.copr:
        host: copr.fedorainfracloud.org
        state: enabled
        name: atim/starship

    - name: Install starship
      become: true
      ansible.builtin.dnf:
        name: starship
        state: present
  tags: terminal

# End of Fedora starship block

- name: Install starship prompt Ubuntu
  become: true
  community.general.snap:
    name: starship
    channel: edge
  when: ansible_facts["os_family"] == "Debian"
  tags: terminal

- name: Copy bash config
  ansible.builtin.copy:
    src: "files/bashrc"
    dest: "{{ ansible_facts['user_dir'] }}/.bashrc"
    mode: "0644"
  tags: terminal

- name: Copy fish config
  ansible.posix.synchronize:
    src: "files/config/fish"
    dest: "{{ ansible_facts['user_dir'] }}/.config/"
  tags: terminal

- name: Copy fastfetch config
  ansible.posix.synchronize:
    src: "files/config/fastfetch"
    dest: "{{ ansible_facts['user_dir'] }}/.config/"
  tags: terminal

- name: Copy ghostty terminal config
  ansible.posix.synchronize:
    src: "files/config/ghostty"
    dest: "{{ ansible_facts['user_dir'] }}/.config/"
  tags: terminal

- name: Copy kitty terminal config
  ansible.posix.synchronize:
    src: "files/config/kitty"
    dest: "{{ ansible_facts['user_dir'] }}/.config/"
  tags: terminal

- name: Change user shell
  block:
    - name: Get shell path
      ansible.builtin.command: which "{{ base_user_shell }}"
      register: shell_path
      changed_when: false

    - name: Make sure shell is located in /etc/shells
      become: true
      ansible.builtin.lineinfile:
        path: /etc/shells
        line: "{{ shell_path.stdout }}"
        state: present

    - name: Set user shell
      become: true
      ansible.builtin.user:
        name: "{{ ansible_facts['user_id'] }}"
        shell: "{{ shell_path.stdout }}"
  tags: terminal

# End of change user shell block
