---
- name: Install neovim
  become: true
  ansible.builtin.dnf:
    name: neovim
    state: present
  when: ansible_distribution == "Fedora"

- name: Install neovim in ubuntu
  become: true
  block:
    - name: Add the neovim ppa repo
      ansible.builtin.apt_repository:
        repo: "ppa:neovim-ppa/unstable"

    - name: Install neovim package
      ansible.builtin.apt:
        name: neovim
        state: present
        update_cache: true

# End of ubuntu neovim installation block

- name: Make sure nvim share directory is absent
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.local/share/nvim"
    state: absent

- name: Make sure nvim config directory is absent
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/.config/nvim"
    state: absent

- name: Copy neovim config directory
  ansible.posix.synchronize:
    src: "files/nvim"
    dest: "{{ ansible_user_dir }}/.config"
# EOF
